### ISSUE TITLE
Consider adding SWH stats

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/codegouvfr#14]
I've added some stats regarding SWH: total number of repos archived by them and ratio. https://github.com/etalab/data-codes-sources-fr/commit/b4e5397fcae9b8de999275ef7454aa1c70140f77

If you want to display this info.

Feel free to ask for other things by opening an issue.

**Comment by bzg** [comment]
Thanks. I reference https://github.com/etalab/codegouvfr/issues/2 here because I guess the two are meant to be done together.

**Comment by bzg** [comment]
Done, thanks!
