### ISSUE TITLE
Don't show organizations with 0 repositories

### ISSUE THREAD

**Issue by bzg** [etalab/codegouvfr#34]
This issue is open to discuss whether it is useful or not to list organizations with no repository.

I'm inclined to simply filter them out.

Cc @AntoineAugusti @ljoubert are you okay with filtering them out?

**Comment by AntoineAugusti** [comment]
Could be useful to know why they went through the creation but did not publish repositories. Maybe not needed in the UI, this can be seen from the data only (but it's not as straightforward).

**Comment by bzg** [comment]
Ok. I suggest to filter these organizations _out_ by default but to add a switch to let the user display them. Perhaps we'll have a better solution in the long term.
