### ISSUE TITLE
Add links to reference database

### ISSUE THREAD

**Issue by pachevalier** [etalab/codegouvfr#35]
Using github id and Wikidata, or je possible to add link to "l'annuaire du service public", which is a reference for public organizations in France.

Here is a sample query :  https://query.wikidata.org/#SELECT%20%3Fgithub%20%3Flannuaire%20%3Fitem%20%3FitemLabel%20WHERE%20%7B%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22fr%2Cen%22.%20%7D%0A%20%20%3Fitem%20%28wdt%3AP31%2F%28wdt%3AP279%2a%29%29%20wd%3AQ31728%3B%0A%20%20%20%20wdt%3AP17%20wd%3AQ142%20%3B%0A%20%20%20%20wdt%3AP2037%20%3Fgithub%20%3B%0A%20%20%20%20wdt%3AP6671%20%3Flannuaire%20.%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%0A%7D%0AORDER%20BY%20%28%3FitemLabel%29

**Comment by pachevalier** [comment]
Here is a simplified version https://query.wikidata.org/#SELECT%20%3Fgithub%20%3Flannuaire%20%3Fitem%20%3FitemLabel%20WHERE%20%7B%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22fr%2Cen%22.%20%7D%0A%20%20%3Fitem%20wdt%3AP2037%20%3Fgithub%3B%0A%20%20%20%20wdt%3AP6671%20%3Flannuaire.%0A%7D%0AORDER%20BY%20%28%3FitemLabel%29

**Comment by bzg** [comment]
Cc @AntoineAugusti : the idea would be to take [comptes-organismes-publics](https://raw.githubusercontent.com/DISIC/politique-de-contribution-open-source/master/comptes-organismes-publics) as input and to get the URL of the public organization on https://www.service-public.fr by retrieving this information on Wikidata - the link could then be added on each organization card in https://code.etalab.gouv.fr/organisations 

@pachevalier will see if he can provide a daily export of this alignment but perhaps this could be integrated on https://github.com/etalab/data-codes-sources-fr in the long run.

**Comment by AntoineAugusti** [comment]
Not super familiar with Wikidata. @pachevalier, you've worked with this. Is there already a CSV export like this somewhere? Some code or documentation to do this?

**Comment by pachevalier** [comment]
I can export the CSV daily if you need it.

**Comment by bzg** [comment]
If it is not too much work, yes, let's start with a daily csv (sent manually? hosted on a repo?)

Then we'll see how to integrate this information in https://code.etalab.gouv.fr/organisations

Thanks!

**Comment by pachevalier** [comment]
I can export it on DataGouv

**Comment by bzg** [comment]
As in "export it manually and upload it manually on data.gouv.fr everyday"?

Otherwise, If your export is automated, let's start with this, others could find it useful too.

If it's not automated, just a sample (python?) script on how to produce the .csv would be a good start for later integration in [data-codes-sources-fr](https://github.com/etalab/data-codes-sources-fr).

Thanks!

**Comment by pachevalier** [comment]
Of course it is automated

**Comment by bzg** [comment]
Ah okay, then please go ahead for sure!

**Comment by pachevalier** [comment]
I'be created two resources on datagouv. Have a look if you can integrate it. https://www.data.gouv.fr/fr/datasets/organisations-de-codegouvfr/

**Comment by pachevalier** [comment]
It would also make sense to link to datagouv. Tell me if you prefer a json format.

**Comment by bzg** [comment]
Nice, thanks!

**Comment by bzg** [comment]
I just implemented this and added an icon/link to organization with official website. Thanks for the idea.
