### ISSUE TITLE
Add explanations under table titles

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/codegouvfr#40]
On `/chiffres`, there are various tables and numbers. I think some explanations text would help non super technical users.

Questions people could ask:
- what's a star?
- what's an org?
- what are these licences? why so many?
- why saving stuff on SWH matters?

**Comment by bzg** [comment]
I have added links to the glossary, now living on its own page. Do you think we should add more verbal explanations within the page? I'm reluctant to go that way: hopefully the page will grow with more self-explanatory figures/graphs.

**Comment by bzg** [comment]
If that's okay for you, I'll close this issue today.

**Comment by AntoineAugusti** [comment]
Yup, this page is better than it was before. Let's see if it's enough!

Thanks for working on this issue
