### ISSUE TITLE
How to deal with organizations with accounts on multiple platforms ?

### ISSUE THREAD

**Issue by pachevalier** [etalab/codegouvfr#41]
Some organizations, such as Etalab, have multiple accounts. For instance Etalab has a framagit account (https://framagit.org/groups/etalab) and a Github account (https://github.com/etalab). 

Therefore Etalab appears twice in the organization page. This may be confusing for users. By the way, when you clic on the link "31 dépôts" at the bottom of the Framagit Etalab card, you get a link to all the Etalab project (219 on Github + 31 on Framagit). This is not very intuitive. 

One solution would be to use the name of the organization + the name of the platform as a slug and card name : "Etalab - Github", "Etalab - Framagit", etc.

Another solution would be to group organizations with multiple accounts.

**Comment by bzg** [comment]
Thanks for the feedback!

> Therefore Etalab appears twice in the organization page. 

This is a very recent change: someone complained that looking for "inria" was only returning the organisation of this name - not all orgas and groups from all forges. The search now matches against the URL of the organisation too, hence "inria" matching more than https://github.com/INRIA.

 > By the way, when you clic on the link "31 dépôts" at the bottom of the Framagit Etalab card, you get a link to all the Etalab project (219 on Github + 31 on Framagit). This is not very intuitive.

Indeed, fixed. Now clicking on this number will only list the organisation repos.

> One solution would be to use the name of the organization + the name of the platform as a slug and card name : "Etalab - Github", "Etalab - Framagit", etc.

I settled with yet another option, which is to display an icon at the footer of each card, showing the GitHub or GitLab icon. I hope this is okay.

> Another solution would be to group organizations with multiple accounts.

I'm reluctant to go that way, I'd rather expose each and every account for now.

**Comment by bzg** [comment]
PS: You can test the new feature now.

**Comment by bzg** [comment]
If that's okay for you, I'll close this issue today.
