### ISSUE TITLE
Tri par organisation

### ISSUE THREAD

**Issue by sfermigier** [etalab/codegouvfr#48]
Actuellement, si on clique sur "Organisation/dépôt" on trie par nom de projet.

Ca serait bien de pouvoir trier par organisation.

Pour cela il faut probablement faire 2 colonnes au lieu d'une.

**Comment by bzg** [comment]
Est-ce que la page [groupes](https://code.etalab.gouv.fr/groupes) ne répond pas en partie à cette demande de visibilité par organisation ? Ou bien le fait de cliquer sur le nom de l'organisation ?

Nous voudrions éviter d'avoir trop de colonnes.

**Comment by sfermigier** [comment]
Est-ce que la page groupes ne répond pas en partie à cette demande de visibilité par organisation ?

=> Non car on perd la vue d'ensemble.

Ou bien le fait de cliquer sur le nom de l'organisation ?

=> Je n'avais pas vu que c'était possible.

Mais globalement, ce qui est le plus inattendu, c'est que le tri sur la première colonne devrait se faire dans l'ordre lexicographique sur les paires (org, repo) alors qu'il se fait uniquement sur le nom du repo. C'est pas intuitif.

**Comment by bzg** [comment]
> Mais globalement, ce qui est le plus inattendu, c'est que le tri sur la première colonne devrait se faire dans l'ordre lexicographique sur les paires (org, repo) alors qu'il se fait uniquement sur le nom du repo. C'est pas intuitif.

Oui, tu as raison, je vais voir ce qu'on peut faire.
