### ISSUE TITLE
Export JSON

### ISSUE THREAD

**Issue by sfermigier** [etalab/codegouvfr#49]
Ca serait bien de pouvoir exporter les données pour pouvoir faire ses propres analyses.

Bon je vois depuis les devtools de Chrome que c'est dispo ici: https://api-codes-sources-fr.antoine-augusti.fr/api/repertoires/all

Mais un lien ou un bouton depuis le site serait plus évident.

**Comment by bzg** [comment]
Merci pour ton retour. Il y a un lien dans le premier paragraphe de https://code.etalab.gouv.fr/apropos: 

> Ces métadonnées sont publiées sur data.gouv.fr ou interrogeables depuis cette API.

https://www.data.gouv.fr/fr/datasets/inventaire-des-depots-de-code-source-des-organismes-publics/

Est-ce que cela répond à la demande ?

**Comment by sfermigier** [comment]
OK
