### ISSUE TITLE
Différencier projets actifs et projets archivés

### ISSUE THREAD

**Issue by sfermigier** [etalab/codegouvfr#50]
Certains projets ont, sur GitHub, un statut "archivé". Ca serait bien de pouvoir les différencier directement depuis la table, car a priori ils sont moins intéressants que les projets actifs.

**Comment by bzg** [comment]
On ne peut malheureusement pas ajouter trop de colonnes à la table.

Aujourd'hui, tu peux soit voir la liste de tous les dépôts, soit demander de ne voir que ceux qui ne sont _pas_ archivés, ce qui nous paraît correspondre au besoin.

Si tu vois une autre manière de faire qui ne surcharge pas l'interface, n'hésite pas à nous détailler ça.

Merci !

**Comment by sfermigier** [comment]
> Si tu vois une autre manière de faire qui ne surcharge pas l'interface, n'hésite pas à nous détailler ça.

=> Mettre en grisé ou ajouter une icone (genre https://fontawesome.com/icons/tombstone ou https://fontawesome.com/icons/archive).

**Comment by bzg** [comment]
En grisé ça me paraît bien. Merci pour l'idée !
