### ISSUE TITLE
Filtre non fonctionnel sur licence WTFPL 

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/codegouvfr#51]
La page https://code.etalab.gouv.fr/?licence=Do%20What%20The%20F*ck%20You%20Want%20To%20Public%20License ne retourne aucun dépôt alors [qu'il en existe bien un](https://github.com/communaute-cimi/gpx-rev-geocode).

Mon hypothèse est que le nom de la licence _Do What The Fuck You Want To Public License_ est transformée par GitHub en _Do What The F*ck You Want To Public License_ dans le JSON, rendant le filtrage inefficace.

**Comment by AntoineAugusti** [comment]
Fixed upstream as well. You can revert your commit in a few days

**Comment by bzg** [comment]
(Why in a few days?) I'll revert the commit when you give me the green light. Thanks for the swift action!

**Comment by AntoineAugusti** [comment]
In a few hours after the data is refreshed 😉
