### ISSUE TITLE
Utiliser csvapi ou data.gouv.fr comme backend

### ISSUE THREAD

**Issue by abulte** [etalab/codegouvfr#52]
Il serait peut-être intéressant d'utiliser [csvapi](https://github.com/etalab/csvapi) sur le jeu de données publié sur data.gouv.fr plutôt qu'une API custom qui ne fait que servir un JSON.

Cf https://csvapi.data.gouv.fr/api/19aa9345f127b95cbaa0e883eb64db7d?_shape=objects&_rowid=hide&_size=50&_offset=0.

Il y a un petit challenge lors de la mise à jour de la liste : 
- si l'URL de la ressource sur data.gouv.fr ne change pas, le hash dans l'URL vers csvapi.data.gouv.fr ne change pas et le cache n'expire jamais
- si l'URL de la ressource change, le hash change et le cache est invalidé MAIS il faut changer le point d'accès vers l'API — dans ce dernier cas ce serait peut-être malin d'utiliser l'API de data.gouv.fr pour aller chercher l'URL de la dernière ressource à jour (le hash est un bête md5)

NB : il est aussi possible de piloter l'apification d'un CSV directement sur csvapi.data.gouv.fr, sans passer par data.gouv.fr. Appel à `/apify?url=xxx` qui renvoie le lien vers l'API : https://github.com/etalab/csvapi#conversion.

**Comment by bzg** [comment]
Hello ! Pourquoi pas, mais quel est le problème que cela résout ?

Indépendamment de la réponse, je vois plusieurs conditions : 

- que `csvapi.data.gouv.fr` soit officiellement en production ;
- que nous puissions avoir tout le `json` d'un coup sans pagination ;
- que les requêtes soient aussi rapides qu'avec la solution actuelle ;
- que le taux de disponibilité soit aussi bon que la solution actuelle.

**Comment by abulte** [comment]
> Hello ! Pourquoi pas, mais quel est le problème que cela résout ?

Souveraineté, dogfooding / cohérence, vie privée. Ca nous donne « les moyens de maintenir une instance ».

> Indépendamment de la réponse, je vois plusieurs conditions :
> 
> * que `csvapi.data.gouv.fr` soit officiellement en production ;

C’est le cas depuis un an.

> * que nous puissions avoir tout le `json` d'un coup sans pagination ;

https://csvapi.data.gouv.fr/api/19aa9345f127b95cbaa0e883eb64db7d?_shape=objects&_rowid=hide&_size=-1&_offset=0

Je suis sûr sur le front pourrait aussi tirer partie d’une « vraie » API avec pagination.

> * que les requêtes soient aussi rapides qu'avec la solution actuelle ;

Pingdom m’annonce 200ms avec le JSON complet plus haut et 1,1 seconde sur https://api-code.etalab.gouv.fr/api/repertoires/all. Good enough?

> * que le taux de disponibilité soit aussi bon que la solution actuelle.

Je te trouve un peu dur. Nous ne sommes pas Github. On peut toutefois s’aligner sur les taux de dispo des sites en .gouv.fr que nous opérons. Les données de disponibilité sont visibles ici https://status.etalab.studio/.

---

Alternative encore plus simple, avec une dispo encore meilleure — surtout si tu n’utilises pas la pagination : taper directement sur un CSV hébergé sur data.gouv.fr.

**Comment by bzg** [comment]
Ce que je voulais dire par "officiellement en production" c'est que `csvapi.data.gouv.fr` soit annoncé à l'écosystème des réutilisateurs de `data.gouv.fr` (c'est pas déjà le cas, si?) et utilisable par d'autres applications, selon une politique à définir (pas déjà le cas non plus, si?).

> Alternative encore plus simple, avec une dispo encore meilleure — surtout si tu n’utilises pas la pagination : taper directement sur un JSON hébergé sur data.gouv.fr.

Oui, ça me paraît plus simple, au moins dans un premier temps. @AntoineAugusti tu en pensesquoi ?

**Comment by AntoineAugusti** [comment]
C'est un débat intéressant. Ce que j'en pense :

- `csvapi.data.gouv.fr` est déjà copieusement utilisé sur `data.gouv.fr`, on a fait quelques commits et quelques déploiements dernièrement. Ceci dit, pour le moment il n'est utilisé que dans le contexte de data.gouv.fr et je pense que l'utiliser sur des projets annexes est intéressant pour identifier les limites, ajustements, vérifier la disponibilité etc
- `csvapi.data.gouv.fr` doit être annoncé à la communauté, c'est sûr. Est-ce production-ready pour les autres utilisateurs ? Difficile à dire. Peut-être pas immédiatement, je dirai après 2-3 autres projets mêmes petits qui l'utilise, ou dans 3-4 mois.

Reste une question pour @abulte : la ressource ne change pas, mais le contenu distant oui. Comment faire expirer le cache ?

Est-ce pour autant une raison pour abandonner l'autre projet ? Pas sûr. csvapi ou l'utilisation du simple fichier JSON permet d'avoir une alternative à l'utilisation actuelle. Mais l'autre dépôt et API permet d'avoir des répertoires et organisations par slug, ce qui n'est pas possible avec les autres solutions. Lié à https://github.com/etalab/api-codes-sources-fr/issues/7

**Comment by bzg** [comment]
Le frontend ne va plus chercher les données directement dans l'API, il va les chercher dans le backend qui va les chercher dans l'API.

@AntoineAugusti penses-tu utile de publier les `.json` dans [data.gouv.fr](https://www.data.gouv.fr/fr/datasets/inventaire-des-depots-de-code-source-des-organismes-publics/)?

Si oui, j'irai les chercher là-bas depuis le backend.

Nous pourrions aussi ajouter les statistiques dans [data.gouv.fr](https://www.data.gouv.fr/fr/datasets/inventaire-des-depots-de-code-source-des-organismes-publics/) pour que j'aille tout chercher là-bas.

**Comment by bzg** [comment]
> @AntoineAugusti penses-tu utile de publier les .json dans data.gouv.fr?
> Si oui, j'irai les chercher là-bas depuis le backend.

Si tu penses que ça a du sens de publier les `.json` sur [data.gouv.fr](https://data.gouv.fr), je réouvre l'issue.
