### ISSUE TITLE
Generate link to search 

### ISSUE THREAD

**Issue by arthurlogilab** [etalab/codegouvfr#56]
It would be nice to have a shareable link to a search in the index. 

For example : 

* go to https://code.etalab.gouv.fr/
* type "offre" in the search textarea
* the URL has changed to https://code.etalab.gouv.fr/#search/offre
* that URL can be shared

**Comment by bzg** [comment]
Thanks a lot for pushing this, I've clean up and documented things a little bit.  Please test it and report any problem.

**Comment by arthurlogilab** [comment]
Wow ! Thanks for implementing this so fast! 

Reading the diff, I tried https://code.etalab.gouv.fr/?s=cubicweb which doesn't seem to work ... has it not yet been shipped in production ?

**Comment by bzg** [comment]
My bad. There was a typo in the https://code.etalab.gouv.fr/apropos page, fixed now.

You can use https://code.etalab.gouv.fr/?q=cubicweb

**Comment by arthurlogilab** [comment]
That's nice. Working now. 

Any chance to get the use case where the URL is rewritten when we fill the field ? So it can be easily be shared without reading the documentation ? Should I enter a separate ticket or should we reopen this one ?

**Comment by bzg** [comment]
It is implemented now, thanks for this idea!

**Comment by arthurlogilab** [comment]
Wow :heart_eyes: ... I'm very impressed on how fast this changed was implemented. Thanks.
