### ISSUE TITLE
L'ordre "Dépôt / Groupe" est contre-intuitif

### ISSUE THREAD

**Issue by camillem** [etalab/codegouvfr#68]
Bonjour, 

Dans une majorité de contextes numériques courants faisant référence à une arborescence, la notation "A/B" induit que B est contenu dans A ; vous avez choisi ici la convention inverse, pour des raisons que j'imagine tout à fait fondées, mais cela reste déroutant _in fine_.

Sans revenir sur le choix de cet ordre inhabituel, serait-il envisageable alors de choisir un séparateur lui aussi inhabituel, pour avertir le lecteur pressé que l'on sort des conventions courantes ?

Par exemple "Dépôt < Groupe  " ?
Merci, 
Camille

**Comment by bzg** [comment]
Bonjour, désolé pour la réponse tardive, et excellente suggestion - ce sera dans la `0.9` qui devrait sortir et être en production cette semaine. Merci !
