### ISSUE TITLE
Le site ne tient pas compte de la configuration linguistique du navigateur dans la redirection de la page d'accueil 

### ISSUE THREAD

**Issue by ele-gall-ac-mineducation** [etalab/codegouvfr#69]
https://code.etalab.gouv.fr/
→ https://code.etalab.gouv.fr/en/repos

indépendamment des réglages des préférences (d’ordre) de langue du navigateur…

peut-être liée à cet ordre :

https://github.com/etalab/codegouvfr/blob/f40d47b6d19a0f0a0d8b98edb4df7d2f78f6bc79/src/cljc/codegouvfr/i18n.cljc#L4

**Comment by bzg** [comment]
Bonjour, je n'arrive pas à reproduire le problème avec des versions récentes de Firefox et de Chrome.

Peux-tu me donner plus de précisions sur le navigateur et sa configuration exacte ?

Merci !

**Comment by bzg** [comment]
Hello @ele-gall-ac-mineducation est-ce que tu as pu tester avec d'autres navigateurs et/ou configurations ?

**Comment by bzg** [comment]
@ele-gall-ac-mineducation je te laisse réouvrir l'issue si jamais tu arrives à reproduire le problème depuis un autre ordinateur ou une autre configuration. Merci !
